---
kind: pipeline
name: ci

steps:
  - name: publish/docker-image
    image: plugins/docker
    settings:
      repo: iknpx/archnode
      purge: true
      insecure: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push
